
    openapi: 3.0.0
    info: 
        title: TEST
        description: 'L5 Swagger OpenApi description'
        version: 1.0.0
    servers:
        - description: 'SwaggerHub API Auto Mocking'
          url: http://127.0.0.1:8000

    paths:
        /api/getprofile/:
            get:
              tags:
                - Edit Profile
              summary: Getprofile
              description: Getprofile
              security:
                - passport: []
              responses:
                200:
                  description: Description
                  content: 
                    application/json:
                      schema:
                        type: string
        /api/updateprofile/:
              post:
                tags:
                  - Edit Profile
                summary: Update Profile
                description: Update Profile
                security:
                  - passport: []
                requestBody:
                  content:
                    multipart/form-data:
                      schema:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
                          mobile:
                            type: string
                          address:
                            type: string
                          salon_type: 
                            type: string  
                          image:
                            type: file
                responses:  
                    200:
                      description: Description
                      content: 
                        application/json:
                          schema:
                            type: string



        /api/deleteprofile/{id}: 
              delete:
               tags: 
                   - Delete Profile
               summary: Delete Profile
               description: Delete Profile
               security:
                  - passport: []
               parameters:
                  - name: id
                    in: path
                    description: id
                    required: true  
                    schema:
                      type: integer
              
               responses:
                  200:
                    description: Description
                    content: 
                      application/json:
                        schema:
                          type: string
        /api/changepassword/:
              post:
                tags:
                  - Change Password
                summary: Change Password
                description: Change Password
                security:
                  - passport: []
                requestBody:
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          old_password:
                            type: string
                          new_password:
                            type: string
                          confirm_password:
                            type: string
                responses:
                  200:
                    description: Description
                    content: 
                      application/json:
                        schema:
                          type: string
        /api/terms/:
            get:
              tags:
                - Terms
              summary: Terms
              description: Terms
              security:
                - passport: []
              responses:
                200:
                  description: Description
                  content: 
                    application/json:
                      schema:
                        type: string

        /api/faqs/:
            get:
              tags:
                - Faqs
              summary: Faqs
              description:  Faqs
              security:
                - passport: []
              responses:
                200:
                  description: Description
                  content: 
                    application/json:
                      schema:
                        type: string

        /api/policies/:
            get:
              tags:
                - Policies
              summary: Policies
              description:  Policies
              security:
                - passport: []
              responses:
                200:
                  description: Description
                  content: 
                    application/json:
                      schema:
                        type: string
        /api/contactus/:
              post:
               tags:
                - Contact Us
               summary: Contact Us
               description: Contact Us
               security:
                  - passport: []
               requestBody:
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
                          mobile:
                            type: string
                          message:
                            type: string
               responses:
                  200:
                    description: Description
                    content: 
                      application/json:
                        schema:
                          type: string

        /api/support/:
              post:
               tags:
                -  Support
               summary: Support
               description:   Support
               security:
                  - passport: []
               requestBody:
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
                          mobile:
                            type: string
                          message:
                            type: string
                          title:
                            type: string  
               responses:
                  200:
                    description: Description
                    content: 
                      application/json:
                        schema:
                          type: string



    components:
        securitySchemes: 
            passport: 
                type: apiKey
                description: Laravel passport oauth2 security.      <br><br> <h4> EXAMPLE - Bearer YourToken </h4><br>
                in: header
                name: authorization
                scheme: https
                flows: 
                    password: 
                        authorizationUrl: http://localhost/oauth/authorize
                        tokenUrl: http://localhost/oauth/token
                        refreshUrl: http://localhost/token/refresh
                        scopes: 
                    
        
            
        
    